apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend/k8s/backend-deployment.yaml
  - backend/k8s/backend-service.yaml
  - backend/k8s/mongo-deployment.yaml
  - backend/k8s/mongo-pvc.yaml
  - backend/k8s/mongo-service.yaml
  - frontend/k8s/frontend-deployment.yaml
  - frontend/k8s/frontend-service.yaml
  - frontend/k8s/ingress.yaml

images:
  - name: elijahgolnik/backend-multistage
    newTag: 9dd372bb688403a7713a0ebbd95691e34f795d6a

  - name: elijahgolnik/frontend
    newTag: 9dd372bb688403a7713a0ebbd95691e34f795d6a