name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build Docker image
          run: docker build -t elijahgolnik/backend-multistage:latest ./backend

        - name: Push image
          run: docker push elijahgolnik/backend-multistage:latest

        - name: Set up kubectl
          uses: azure/setup-kubectl@v3

        - name: Set kubeconfig
          run: |
            mkdir -p ~/.kube
            echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

        - name: Deploy to Kubernetes
          run: |
            kubectl apply -f backend/k8s/
            kubectl rollout restart deployment backend

        