name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Set image tag
          run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

        - name: Build Docker Image
          run: docker build -t elijahgolnik/backend-multistage:${IMAGE_TAG} ./backend

        - name: Push image
          run: docker push elijahgolnik/backend-multistage:${IMAGE_TAG}

        - name: Build Frontend Image
          run: docker build -t elijahgolnik/frontend:${IMAGE_TAG} ./frontend

        - name: Push Frontend Image
          run: docker push elijahgolnik/frontend:${IMAGE_TAG}

        - name: Set up kubectl
          uses: azure/setup-kubectl@v3

        - name: Set Kubeconfig
          run: echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

        - name: Update Kubernetes Deployment Image
          run: |
            kubectl apply -f backend/k8s/
            kubectl set image deployment/backend backend=elijahgolnik/backend-multistage:${IMAGE_TAG}

        
            

        